import { MigrationInterface, QueryRunner } from "typeorm";

export class Migartion1748344827526 implements MigrationInterface {
    name = 'Migartion1748344827526'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" ADD "created_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" ADD "updated_timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_type" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_models" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_llm_channels" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_sd_models" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_canvas_applications" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_knowledge_bases_sql" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_media_files" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_apikey" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_filters" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tags" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_assets_authorization" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tag_relations" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_marketplace_tags" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_asset_tag_relations" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_workflows" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_servers" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model_server_relations" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_comfyui_model" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_themes" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_executions" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_conversation_apps" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_invites" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_join_requests" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_teams" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_team_members" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_users" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_observability" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_oneapi_users" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_system_configurations" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credential_types" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_credentials" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_server" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools_trigger_types" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_tools" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_chat_sessions" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_pages" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_execution" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_page_group" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_metadatas" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_triggers" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" DROP COLUMN "updated_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" ADD "updated_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" DROP COLUMN "created_timestamp"`);
        await queryRunner.query(`ALTER TABLE "monkeys_workflow_templates" ADD "created_timestamp" bigint NOT NULL DEFAULT '1748344775167'`);
    }

}
