export const listUgcWorkflowsMock = {
  code: 200,
  data: [
    {
      _id: '65f7a5e06db7950b6d76f4c7',
      workflowId: '65f5b3106db7950b6d76f292',
      workflowDef: {
        tasks: [
          {
            __alias: {
              description: '使用本地模型或训练后的模型生成文本',
              title: '文本生成（本地模型）',
            },
            inputParameters: {
              llmModelId: '',
              max_tokens: 1024,
              temperature: 0.3,
              text: '',
            },
            name: 'llm_infer',
            taskReferenceName: 'llm_infer_PdzmTwqF',
            type: 'SIMPLE',
          },
        ],
      },
      variables: [
        {
          default: 'https://static.infmonkeys.com/RYkpbJ_kaito.jpg',
          displayName: '测试',
          name: 'u0ot7ln9',
          type: 'file',
        },
      ],
      output: null,
      name: '测试工作流',
      desc: null,
      logo: null,
      tagIds: [],
      assetType: 'workflow',
      description: '',
      iconUrl: '',
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      activated: true,
      createdTimestamp: 1710728672595,
      updatedTimestamp: 1710736415158,
      isDeleted: false,
      hidden: false,
      validated: true,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      version: 2,
      md5: 'b105b7efec65edb0f560a0f58d351449',
      validationIssues: [],
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65b7c58b1fa99b9854c3a11f',
      workflowId: '65b7c58b1fa99b9854c3a11e',
      workflowDef: {
        tasks: [
          {
            name: 'do_while',
            type: 'DO_WHILE',
            taskReferenceName: 'do_while_bpy394ks',
            inputParameters: {
              mode: 'expression',
              listToLoopOver: null,
            },
            loopCondition: "if ($.do_while_bpy394ks['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'sub_workflow',
                taskReferenceName: 'sub_workflow_nested_9h75pepn',
                type: 'SUB_WORKFLOW',
                inputParameters: {
                  name: '65b7d44f1fa99b9854c3a139',
                  version: 1,
                },
                subWorkflow: {
                  workflowDef: {
                    tasks: [
                      {
                        name: 'do_while',
                        type: 'DO_WHILE',
                        taskReferenceName: 'do_while_7rvri6ir',
                        inputParameters: {
                          mode: 'expression',
                          listToLoopOver: null,
                        },
                        loopCondition: "if ($.do_while_7rvri6ir['iteration'] < 1) { false; } else { true; }",
                        loopOver: [
                          {
                            name: 'fake_node',
                            taskReferenceName: 'fake_node_f8ux154m',
                            type: 'SIMPLE',
                          },
                        ],
                      },
                    ],
                  },
                  name: 'sub_workflow_nested_9h75pepn',
                  iconUrl: 'emoji:🍀:#ceefc5',
                  description: '',
                },
              },
            ],
          },
          {
            name: 'collect_dowhile_output',
            type: 'SIMPLE',
            taskReferenceName: 'collect_dowhile_output_uaf100lp',
            inputParameters: {
              doWhileTaskReferenceName: 'do_while_bpy394ks',
              jsonPathExpression: null,
            },
          },
        ],
      },
      name: '嵌套子流程拍平测试',
      description: '',
      iconUrl: 'emoji:🦊:#434343',
      assetType: 'workflow',
      variables: [],
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      activated: true,
      createdTimestamp: 1706542475484,
      updatedTimestamp: 1709651369605,
      isDeleted: false,
      hidden: false,
      validated: true,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      output: null,
      version: 1,
      md5: '15a1eddfc4cb2f376d54fdfcd1d7e668',
      validationIssues: [],
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65b782321fa99b9854c3a0a0',
      workflowId: '65b77da61fa99b9854c3a089',
      workflowDef: {
        tasks: [
          {
            name: 'do_while',
            type: 'DO_WHILE',
            taskReferenceName: 'do_while_iv5bdgtu',
            inputParameters: {
              mode: 'expression',
              listToLoopOver: null,
            },
            loopCondition: "if ($.do_while_iv5bdgtu['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'sub_workflow',
                taskReferenceName: 'sub_workflow_nested_inh88x3s',
                type: 'SUB_WORKFLOW',
                inputParameters: {
                  name: '65b8bd981cf9b1e26c63047e',
                  version: 1,
                },
              },
            ],
          },
          {
            name: 'text_to_image',
            type: 'SIMPLE',
            taskReferenceName: 'text_to_image_l7gbpmgk',
            inputParameters: {
              modelId: 'sd',
              prompt: 'a man',
              negativePrompt: 'EasyNegative',
              batchCount: 1,
              width: 512,
              height: 512,
              samplingStep: 20,
              cfgScale: 7,
              mask: null,
              inpaintingMaskInvert: false,
              seed: -1,
              samplerName: 'Euler a',
              restoreFaces: false,
              enableHr: false,
              hrScale: 2,
              hrUpscaler: 'Latent',
              denoisingStrength: 0.3,
              controlNetEnabled: false,
              controlNetModule: 'tile_resample',
              controlNetModel: 'control_v11f1e_sd15_tile [a371b31b]',
              controlNetWeight: 1,
              controlNetGuidanceStrength: 1,
              controlNetInputImage: 'https://sample.com/sample.png',
              controlNetProcessorRes: 512,
              controlNetPixelPerfect: true,
              controlNetNoDetectmap: true,
            },
          },
        ],
      },
      variables: [],
      output: null,
      name: '嵌套测试',
      desc: null,
      logo: null,
      tagIds: [],
      assetType: 'workflow',
      description: '',
      iconUrl: 'emoji:👀:#fadebb',
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      activated: true,
      createdTimestamp: 1706525234440,
      updatedTimestamp: 1706605976601,
      isDeleted: false,
      hidden: false,
      validated: true,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      version: 4,
      validationIssues: [],
      md5: '5530cc41277c52c35ee5d61a7233506c',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65b4bb6f4fc515e62d888c29',
      assetType: 'workflow',
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      createdTimestamp: 1706343279692,
      updatedTimestamp: 1706343303370,
      iconUrl: 'emoji:😇:#ceefc5',
      name: '用户交互测试工作流  2',
      description: '',
      isDeleted: false,
      workflowId: '65b4bb6f4fc515e62d888c28',
      version: 1,
      activated: true,
      validated: true,
      workflowDef: {
        tasks: [
          {
            name: 'human',
            type: 'HUMAN',
            taskReferenceName: 'human_g8ltq5h8',
            inputParameters: {
              diplayContent: ['世界', '你好', '！'],
              outputType: 'array-join',
              arrayJoinSeparator: null,
            },
            __alias: {
              title: '用户交互',
              description: '我是属于测试工作流 2 的',
              icon: 'emoji:⏸️:#fef8a3',
            },
          },
        ],
      },
      variables: [],
      output: null,
      hidden: false,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      validationIssues: [],
      md5: '5c321040b876d92edda4655e4bde54e8',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65b2239b2dd2571fb874e59c',
      workflowId: '65b2239b2dd2571fb874e59b',
      workflowDef: {
        tasks: [
          {
            name: 'human',
            type: 'HUMAN',
            taskReferenceName: 'human_g8ltq5h8',
            inputParameters: {
              diplayContent: ['世界', '你好', '！'],
              outputType: 'array-join',
              arrayJoinSeparator: null,
            },
            __alias: {
              title: '用户交互',
              description: '我是属于测试工作流的',
              icon: 'emoji:⏸️:#fef8a3',
            },
          },
        ],
      },
      name: '用户交互测试工作流',
      description: '',
      iconUrl: 'emoji:😇:#fef8a3',
      assetType: 'workflow',
      variables: [],
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      activated: true,
      createdTimestamp: 1706173339379,
      updatedTimestamp: 1706607828686,
      isDeleted: false,
      hidden: false,
      validated: true,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      output: null,
      version: 1,
      md5: '60408888106dd3c366684ebbcbffaea8',
      validationIssues: [],
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65b115ace2acf48f8ae7b3d8',
      workflowId: '65b115ace2acf48f8ae7b3d7',
      workflowDef: {
        tasks: [
          {
            name: 'chatgpt_with_prompt',
            type: 'SIMPLE',
            taskReferenceName: 'chatgpt_with_prompt_b3km745q',
            inputParameters: {
              systemMessage: '你是一名 PHP 工程师',
              humanMessage:
                '请完善下面的代码\n<?php\n// 使用 Cookie 记录用户选择的日期和日程\n?>\n\n<!DOCTYPE html>\n<html lang="en">\n\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Calendar</title>\n    <style>\n        td {\n            height: 50px;\n            text-align: center;\n            border: 2px solid;\n            cursor: pointer;\n        }\n        td:hover { background: #f0f0f0; }\n        .active {background: #d3d3d3;}\n        td:active {background: #d3d3d3;}\n    </style>\n</head>\n\n<body\n    style="width: 100vw;height: 100vh;margin: 0;display: flex;align-items: center;justify-content: center;background:#333;">\n    <div style="width: 80%;height: 60%;background: white;border-radius: 10px;padding: 16px;">\n        <h1 style="line-height:1;margin:0;">日程表</h1>\n        <div style="width:100%;display:flex">\n            <div style="width:60%">\n                <form action="calendar.php" method="post">\n                    <table style="width: 50%;margin-top: 16px;">\n                        <tr>\n                            <th>日</th>\n                            <th>一</th>\n                            <th>二</th>\n                            <th>三</th>\n                            <th>四</th>\n                            <th>五</th>\n                            <th>六</th>\n                        </tr>\n                        <tr>\n                            <td><input type="hidden" name="selected_date" value="1" />1</td>\n                            <td><input type="hidden" name="selected_date" value="2" />2</td>\n                            <td><input type="hidden" name="selected_date" value="3" />3</td>\n                            <td><input type="hidden" name="selected_date" value="4" />4</td>\n                            <td><input type="hidden" name="selected_date" value="5" />5</td>\n                            <td><input type="hidden" name="selected_date" value="6" />6</td>\n                            <td><input type="hidden" name="selected_date" value="7" />7</td>\n                        </tr>\n                    </table>\n                    <div style="width:50%;height: 1px;background: black;margin: 10px 0;"></div>\n                    <input placeholder="请输入日程" type="text" name="new_schedule" />\n                    <input type="submit" value="submit" />\n                    <input type="submit" value="checkout" />\n                </form>\n            </div>\n\n            <div style="width:40%">\n                <?php\n                // 显示选择的日程或当日日程\n                ?>\n            </div>\n        </div>\n    </div>\n    <script>\n        document.querySelectorAll(\'td\').forEach(function (cell) {\n            cell.addEventListener(\'click\', function () {\n                const date = this.querySelector(\'input\').value;\n                document.querySelector(\'input[name="selected_date"]\').value = date;\n                document.querySelectorAll(\'td\').forEach(function (cell) {\n                    cell.classList.remove(\'active\');\n                });\n                this.classList.add(\'active\');\n            });\n        });\n    </script>\n</body>\n</html>',
              modelType: 'gpt-4-32k',
              temperature: 0.2,
            },
          },
        ],
      },
      name: '测试工作流',
      description: '',
      iconUrl: 'emoji:🫢:#434343',
      assetType: 'workflow',
      variables: [
        {
          type: 'string',
          displayName: '对话内容',
          default: '请列出一条复杂的加法算式',
          name: 'owlx3xy8',
        },
      ],
      teamId: '6433d19aeb120fec53f0c290',
      creatorUserId: '6433d199eb120f3c33f0c28f',
      activated: true,
      createdTimestamp: 1706104236646,
      updatedTimestamp: 1710395669188,
      isDeleted: false,
      hidden: false,
      validated: true,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      output: [
        {
          key: 'output1',
          value: '${chatgpt_with_prompt_b3km745q.output.response}',
        },
      ],
      version: 1,
      md5: 'da60e3e2d29fccf5726783e59c709245',
      validationIssues: [],
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '65a73651c43e7cd22fecb39f',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1705457233747,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🫢:#434343',
      isDeleted: false,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      md5: 'fa40d9219bae261300cda86be049deb3',
      name: '无表单测试工作流',
      output: [],
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1706609013276,
      validated: true,
      validationIssues: [],
      variables: [
        {
          type: 'string',
          displayName: '测试',
          name: 'yk4hc0qc',
          typeOptions: {
            assetType: 'workflow',
          },
          default: '65b115ace2acf48f8ae7b3d7',
        },
      ],
      version: 1,
      workflowDef: {
        tasks: [
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_3um2swxv',
            inputParameters: {
              parameters: {
                url: '${workflow.input.yk4hc0qc}',
              },
              sourceCode: 'return $.url;',
            },
          },
          {
            name: 'sub_workflow_65b2239b2dd2571fb874e59b',
            type: 'SUB_WORKFLOW',
            taskReferenceName: 'sub_workflow_65b2239b2dd2571fb874e59b_euwv6qsn',
            inputParameters: {
              version: 1,
              name: '65b2239b2dd2571fb874e59b',
            },
          },
          {
            name: 'do_while',
            type: 'DO_WHILE',
            taskReferenceName: 'do_while_sy0xuk9z',
            inputParameters: {
              mode: 'expression',
              listToLoopOver: null,
            },
            loopCondition: "if ($.do_while_sy0xuk9z['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'send_request',
                type: 'SIMPLE',
                taskReferenceName: 'send_request_xt26jrm2',
                inputParameters: {
                  url: '111',
                  method: 'POST',
                  content_type: 'application/json',
                  data: '222',
                  response_type: 'application/json',
                },
              },
            ],
          },
          {
            name: 'collect_dowhile_output',
            type: 'SIMPLE',
            taskReferenceName: 'collect_dowhile_output_cc0vm9mk',
            inputParameters: {
              doWhileTaskReferenceName: 'do_while_sy0xuk9z',
              jsonPathExpression: null,
            },
          },
        ],
      },
      workflowId: '65a73651c43e7cd22fecb39e',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '659bf9ac4dcf44c2beab368f',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1704720812632,
      creatorUserId: '64e490720091bd4b12967122',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🦿:#434343',
      isDeleted: false,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      name: '并行执行节点测试',
      output: [
        {
          key: 'output1',
          value: '${code_6faflm89.output.data}',
        },
      ],
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1704720812632,
      validated: false,
      variables: [
        {
          type: 'string',
          displayName: '哦',
          default: '哦',
          name: 'i0ytmjb7',
        },
      ],
      version: 3,
      workflowDef: {
        name: '659bc1294e1c28ccdeb93440',
        tasks: [
          {
            name: 'fork_task',
            type: 'FORK_JOIN',
            taskReferenceName: 'fork_task_al3ljb7z',
            inputParameters: {
              joinOn: ['all'],
            },
            forkTasks: [
              [
                {
                  name: 'code',
                  type: 'SIMPLE',
                  taskReferenceName: 'code_6faflm89',
                  inputParameters: {
                    sourceCode: "return '你好，';\n",
                  },
                },
              ],
              [
                {
                  name: 'code',
                  type: 'SIMPLE',
                  taskReferenceName: 'code_rx10c2cv',
                  inputParameters: {
                    sourceCode: "return '世界！';",
                  },
                },
              ],
            ],
            __joinTaskId: 'notification_join_2oaeegcj',
          },
          {
            name: 'notification_join',
            taskReferenceName: 'notification_join_2oaeegcj',
            type: 'JOIN',
            joinOn: ['code_6faflm89', 'code_rx10c2cv'],
            __forkTaskId: 'fork_task_al3ljb7z',
          },
        ],
      },
      workflowId: '659bc1294e1c28ccdeb93440',
      user: {
        _id: '64e490720091bd4b12967122',
        photo: 'https://static.infmonkeys.com/avatars/1704210883043.jpg',
        name: '宫业梓',
        phone: '180****9589',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '659bdef84e1c28ccdeb934c3',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1704713976072,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🤏:#d9caf8',
      isDeleted: false,
      masterWorkflowId: null,
      masterWorkflowVersion: null,
      name: '选择节点测试',
      output: null,
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1704714431962,
      validated: false,
      validationIssues: [
        {
          taskReferenceName: 'switch_lymvkfzc',
          issueType: 'ERROR',
          humanMessage: {
            en: 'Properity evaluatorType is required.',
            zh: '规则类型必填参数未配置',
          },
          detailReason: {
            name: 'evaluatorType',
            type: 'VALUE_REQUIRED',
          },
        },
        {
          taskReferenceName: 'switch_lymvkfzc',
          issueType: 'ERROR',
          humanMessage: {
            en: 'Properity expression is required.',
            zh: '表达式必填参数未配置',
          },
          detailReason: {
            name: 'expression',
            type: 'VALUE_REQUIRED',
          },
        },
      ],
      variables: [],
      version: 1,
      workflowDef: {
        name: '659bdef84e1c28ccdeb934c2',
        tasks: [
          {
            name: 'human',
            type: 'HUMAN',
            taskReferenceName: 'human_i9b4z52a',
            inputParameters: {
              diplayContent: ['switchTrue', 'switchFalse'],
              outputType: 'array-join',
              arrayJoinSeparator: null,
            },
          },
          {
            name: 'switch',
            type: 'SWITCH',
            taskReferenceName: 'switch_lymvkfzc',
            inputParameters: {
              parameters: {
                value: '${human_i9b4z52a.output.selected}',
              },
            },
            evaluatorType: 'value-param',
            expression: 'value',
            decisionCases: {
              switchTrue: [
                {
                  name: 'chatgpt_with_prompt',
                  type: 'SIMPLE',
                  taskReferenceName: 'chatgpt_with_prompt_ucy6bnrm',
                  inputParameters: {
                    systemMessage: '你是一名智能助手',
                    humanMessage: '请写一条复杂的加减法算式',
                    modelType: 'gpt3',
                    temperature: 1,
                  },
                  __alias: {
                    title: 'switchTrue',
                    icon: 'emoji:💬:#c15048',
                  },
                },
              ],
              switchFalse: [
                {
                  name: 'chatgpt_with_prompt',
                  type: 'SIMPLE',
                  taskReferenceName: 'chatgpt_with_prompt_x1n8erzs',
                  inputParameters: {
                    systemMessage: '你是一名智能助手',
                    humanMessage: '请写一条复杂的乘除法算式',
                    modelType: 'gpt3',
                    temperature: 1,
                  },
                  __alias: {
                    title: 'switchFalse',
                    icon: 'emoji:💬:#c15048',
                  },
                },
              ],
            },
          },
        ],
      },
      workflowId: '659bdef84e1c28ccdeb934c2',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '656fee1cea83eb8c2a9af73d',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1701834268996,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🙃:#434343',
      isDeleted: false,
      masterWorkflowId: null,
      name: '数据可视化示例',
      output: null,
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1701834350135,
      validated: true,
      validationIssues: [],
      variables: [],
      version: 1,
      workflowDef: {
        name: '656fee1cea83eb8c2a9af73d',
        tasks: [
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_hh88nvvg',
            inputParameters: {
              parameters: {},
              sourceCode:
                '\n// 您可以在上述的执行参数中定义需要引用的变量，例如您定义了一个名为 url 的变量，可以通过 $.url 进行引用。您还可以通过 require 引用需要的包。\n// 此 JS 沙箱环境支持 Node.js 14 版本，支持 async/await 语法。\n// 最终您需要通过 return 语句返回最终的结果。\n\nreturn {\nresult: ["http://baidu.com", "http://baidu.com", "http://baidu.com", "https://baidu.com"]\n}\n',
            },
            __alias: {
              title: 'URL测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_9knbahun',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return ["这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]',
            },
            __alias: {
              title: '文本测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_rikkvwrj',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return ["https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png", "https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png", "https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png", "https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png"]',
            },
            __alias: {
              title: '图片测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_x1afxaxg',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return ["https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]',
            },
            __alias: {
              title: '图文混合测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_rf9lb7is',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return ["https://baidu.com",  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." ,"https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "https://baidu.com"]',
            },
            __alias: {
              title: '全部混合测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_laumcl7p',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return {\n    result1: "这是一条长文本这是一条长文本这是一条长文本这是一条长文本这是一条长文本这是一条长文本这是一条长文本这是一条长文本",\n    result2: [\n        "这是另一条长文本这是另一条长文本这是另一条长文本这是另一条长文本",\n        "https://static.infmonkeys.com/artworks/7c3942ac926a11ee994f00163e5b3d1e.png",\n    ],\n    result3: "https://baidu.com"\n}',
            },
            __alias: {
              title: '混合嵌套 object 测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_ot6goh7m',
            inputParameters: {
              parameters: {},
              sourceCode:
                'return {\n  data: [\n    {\n      instruction: "这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本",\n    },\n    {\n      instruction: "这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本",\n    },\n    {\n      instruction: "这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本",\n    },\n    {\n      instruction: "这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本",\n    },\n    {\n      instruction: "这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本这是一段测试文本",\n    },\n  ],\n}',
            },
            __alias: {
              title: '超多层级嵌套',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_jbuao0to',
            inputParameters: {
              parameters: {},
              sourceCode: 'return {}',
            },
            __alias: {
              title: '空数据测试',
              icon: 'emoji:🖥️:#434343',
            },
          },
        ],
      },
      workflowId: '656fee1cea83eb8c2a9af73d',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '656dd42e36c95999b726c7df',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1701696558645,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '使用GPT和SD同时生成小红书、快团团的文案、标题、图片',
      forkFromId: '65670f449f17bc4d70144f68',
      hidden: false,
      iconUrl: 'emoji:📲:#ceefc5',
      isDeleted: false,
      masterWorkflowId: null,
      name: '小红书和快团团营销内容生成_clone',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1705561277291,
      validated: true,
      validationIssues: [],
      variables: [
        {
          displayName: '请你上传商品图',
          type: 'string',
          default: 'https://static.infmonkeys.com/frame/files/upload/1697685973769_workflow.png',
          name: 'qp9ho86z',
        },
        {
          displayName: '请输入你的商品名称',
          type: 'string',
          default: '香水',
          name: 'z6gxu0yo',
        },
        {
          displayName: '请输入你的商品卖点',
          type: 'string',
          default: '秋天的黄菊味、天然环保、包装设计、持久度、价格',
          name: 's44sf74k',
        },
      ],
      version: 1,
      workflowDef: {
        tasks: [
          {
            name: 'chatgpt_with_prompt',
            taskReferenceName: 'chatgpt_with_prompt_e6efaty3',
            type: 'SIMPLE',
            inputParameters: {
              systemMessage:
                '# 任务：我将告诉你我要售卖的产品，以及产品的卖点，请你根据[示例]里的内容，帮我写 10 条小红书的标题，来吸引更多用户购买我的产品。# 示例：美食类：1. 宿舍党必囤！会一直回购的素食！量多又便宜2. 四川朋友推荐的..好好吃啊！！忍不住回购！！！！3. 天热就想吃一口酸辣凉拌面！太过瘾！4. 再发一遍！多少个夜晚靠它来掉秤！！美妆类：1. 少年感秘诀｜男士如何对抗初老2. 宝藏小众护肤好物｜开挂了，求别停产3. 懒人必备‼️ 卸妆油界「黑马」💧清爽不闷痘4. 告别洗脸焦虑 打工人必备洗卸合一宝藏洁面5. 震惊我一万年！！！因为它我从此相信了平替穿搭类：1. 早春毛衣ootd🌞女儿说“妈妈，你好帅呀”2. 精致通勤LOOK 要潇洒也要漂亮3. 四月就是穿白衬衣的季节呐🍃4. 沦陷了！酷boy骑平衡车的炸街日常😎5. 轻熟学院派穿搭🔗解封后穿出新花样居家好物类：1. 🏠小镇loft小院改造4！🌷门帘DIY详细教程2. 惊呆了🔥感谢网友的破壁机清洗小妙招!3. 沉浸式宅家✨懒人的智能生活有多爽❓4. 居家不慌张｜囤货小指南5. 这个烤火神器我怎么没早点发现|营地取暖其它好物种草：1. 神仙电动车带娃出门超安心，再也不怕堵车啦2. 介个洗发水太懂油扁塌！头发蓬松全靠它！3. 居家de快乐和幸福感🎬投影仪闲不住了！4. 独处的时间有它们的陪伴一点也不会孤单5. 没忍住，一口气入了四五个，是真值！# 要求：1.除了五个小红书标题，请你不要输出任何其它东西。2.每一个标题的字数控制在 10 个字以内3.每一个标题都至少有一个emoji。',
              humanMessage: '我的商品是：[${workflow.input.z6gxu0yo}]商品的卖点是：[${workflow.input.s44sf74k}]',
              modelType: 'gpt4',
            },
            __alias: {
              title: '小红书标题生成',
              icon: 'emoji:🍠:#f2c1be',
            },
          },
          {
            name: 'chatgpt_with_prompt',
            taskReferenceName: 'chatgpt_with_prompt_j3i56c0c',
            type: 'SIMPLE',
            inputParameters: {
              systemMessage:
                '# 角色：你是一个世界一流的小红书营销大师，擅长在小红书上通过图文笔记来销售商品。# 任务：请你根据我给你的商品名称和商品卖点，写一篇小红书的种草笔记文案。# 知识：小红书的带货文案写法如下：第一段：以“我"的身份写笔记，拉近距离，同时说出大家面临的眼部护理困扰。例如：我非常害怕长眼袋，但是眼部按摩无法消除眼袋，又不想去打水光针。做了一堆功课后发现了三高法。第二段：使用产品卖点+用户收益的写法，对产品特点进行一个总体介绍。例如：高科技+高性价比，它能让你的皮肤紧致饱满。第三段：利用产品使用方法+使用体验模板，分步骤写出产品使用方法和使用后的效果，加深用户对产品的印象。例如：24K纯镀金探头贴着皮肤从眼角缓慢地向眼尾滑动，探头轻微震动，这种电流感让人痴迷，感觉我的黑眼圈就在这震动里消失了。# 要求：1. 文案字数在1000字以内。2. 最好每个自然段不超过两句话，两个自然段之间用分隔符“-”隔开。3. 文案里可以加入 emoji，让它看起来更加生动活泼。4. 用一个女孩子向她的闺蜜推荐好产品的语气来写这一段文案。5. 文案的最后打上和内容匹配的标签。# 示例文案：我宣布！！这就是黄皮/早8人的作弊神器！以前看到素颜霜我都会光速跑开💨香木源海葡萄珍珠素颜霜太绝了！！完全打破了我对素颜霜的刻板印象👋随便抹抹就有妈生冷白皮的feel～清透又自然！早8美美无痛出门✌！-它的质地我真的爱惨了！！是淡淡的薄荷绿色敲美丽🍃不是色素添加噢！就是藻类天然成分本身的颜色可以很好的中和红痘印和面部泛红巨丝滑好推开！感觉像把薄荷冰淇淋涂在脸上🍦里面添加了珍珠粉/贝壳硬蛋白所以皮肤还会有好看的微微光泽感！贼显质感✨！！早上就算是睡迟了也不用担心！有它5分钟快速出门！几秒钟和暗沉蜡黄Say bye👋 整体肤色🆙！暗黄肌、熬夜肌终于有翻身的一天了呜呜😭-这瓶我最近真是越用越喜欢！！一整个沉醉在伪素颜的世界里了哈哈哈哈😎#伪素颜 #平价素颜霜 #淡颜系 #快速出门妆 #早八妆容 #早八人必备 #日常妆容打卡好的，你应该明白我的意思了。请你根据我的需求生成文案。',
              humanMessage: '商品名称：[${workflow.input.z6gxu0yo}]商品卖点：[${workflow.input.s44sf74k}]',
              modelType: 'gpt4',
            },
            __alias: {
              title: '小红书文案生成',
              icon: 'emoji:🍠:#f2c1be',
            },
          },
          {
            name: 'chatgpt_with_prompt',
            taskReferenceName: 'chatgpt_with_prompt_xr2kbvqa',
            type: 'SIMPLE',
            inputParameters: {
              systemMessage:
                "# 角色：你现在是一个世界一流的文案大师,擅长写出情绪饱满的文案。# 任务：Let's think step by step.请你根据[示例]中文案样式，根据我提供给你的{商品名称}和{商品卖点}，写出以下风格的文案。# 示例：<示例1>云南绿植团 💐-𝟏-💐一年能开300天· 微型月季丨果汁阳台🍊仿佛是浇了芬达种出来的🧡好看｜好养｜容易爆花🤣⛱早期果汁橙色｜后期粉白色👉🏻哇塞！！会变色的！！「在我家阳台种出一个飘着花香味的春天🍊」养成系盆栽的成就感☀️比花店里买的任何一束都有意义😍</示例1><示例2>🇫🇷New Angance玻尿酸面膜▲秋冬深层补水｜补完还给你锁住，敷后可以不洗～润润软糯的！玻尿酸精华足足的，但不会留下来修复补水效果赞到爆！医用级别的原液【白膜补水修复｜黑膜抗老滋养】</示例2><示例3>🎁美国小众香薰📜P.F.CANDLE.CO香氛基本都偏木质调🪵清新淡雅 舒适自然经典的棕色玻璃瓶身🟤复古牛皮纸质的贴纸带你感受满满的复古情怀</示例3>",
              humanMessage:
                '# 以下是这次任务的背景信息商品名称：${workflow.input.z6gxu0yo}商品卖点：${workflow.input.s44sf74k}',
              modelType: 'gpt4',
            },
            __alias: {
              title: '快团团标题生成',
              icon: 'emoji:💬:#fef8a3',
            },
          },
          {
            name: 'chatgpt_with_prompt',
            taskReferenceName: 'chatgpt_with_prompt_57mh4woa',
            type: 'SIMPLE',
            inputParameters: {
              systemMessage:
                '# 角色：你现在是一个世界一流的文案大师，擅长写出情绪饱满且富有煽动性的商品文案。# 任务：请你根据[示例]中的文案内容，根据我告诉你的商品名称和商品卖点，写出相似风格的文案。# 示例：<示例1>如果说薰蜡烛带来的感官体验是跳跃的音符那么线香就是轻雾缭绕的虎幻 更添一丝神秘从手工牛皮纸的外包装 再到香型木芯的选用足以看出品牌的用心相信总会有一种味道能唤起你和时光之间的联系，让你闻到恋爱的味道又或者小时候的味道木芯呈现出的日时光和舒适的感觉更是这款线香的迷人之处🖼点上一支喜欢的线香 享受一下午的美好时光</示例1><示例2>🌄P.F CANDLE的新系列Sunset灵感来自于20世纪70年代的加州夏季四种怀旧气味中的香锥意在代表一天中的时间正午、黄昏、夜晚、午夜适用地平线、大地色调和太阳形状来唤起一种朦胧的70年代加州氛围坚持天然植物萃取，还原纯正自然的香气</示例2><示例3>关于New Angance：这款面膜，是被同行专业人士推荐目前在我心中的片装面膜里，排行前三【白色】主打补水修复在我非常干燥枯竭时，它的补水效果很明显洗完澡，紧紧绷绷，用它贴一片皮肤立马可以补进去水每一层都浸透地很彻底！而且它的面膜纸特别服帖 这一点我非常喜欢！膜布特别舒服真的很重要加上精华液又多 每次连脖子一起了这款面膜非常安全，打完水光也可以直接用我每次打完水光都是连用几天这个大写的赞！！一定要推荐给你们懂的人都是5盒的囤着因为好用呀~</示例3><示例4>我要在自家阳台种出果汁般的夏天🍊如果说常常买花是浪漫的事那目光所及种着花的，一定是浪漫的人👉🏻从绿叶到生长出小花苞👉🏻从小花苞盛开到大朵的裙摆怎么会是「成就感」三个字所能涵括的呢❔今儿，绝不只是一束花过过眼瘾，闻一阵花香那么简单我要种它个三年两载📅🌄 看它花开花谢，一次又一次🌄 看它开枝散叶，一枝又一枝开花劳模 · 微型月季丨果汁阳台🧡此月季非彼月季，不是豪放艳丽的大朵而是层层叠叠🔜可爱的微型月季名字我太喜欢了，果汁阳台是啊！就是一阳台果汁色的花花仿佛是浇了芬达，才种出来的月季到手就是盆栽（自己种，多好玩呀🤣⚠️绿叶中带几个花苞，需要自己细心养护哦⚠️养个十来天差不多就开花了，可好看了⚠️收到后务必浇水，浇透，就算有点蔫了，过一夜也能恢复精神（就是运输路上缺水了，补点水就行了！！</示例4>',
              humanMessage:
                '# 本次任务背景信息商品名称：[ ${workflow.input.z6gxu0yo}]商品卖点：[ ${workflow.input.s44sf74k}]',
              modelType: 'gpt4',
            },
            __alias: {
              title: '快团团文案生成',
              icon: 'emoji:💬:#fef8a3',
            },
          },
          {
            name: 'rembg',
            type: 'SIMPLE',
            taskReferenceName: 'rembg_gy19jwbe',
            inputParameters: {
              imageUrl: '${workflow.input.qp9ho86z}',
              model: 'u2net',
              onlyMask: true,
              extras: null,
            },
          },
          {
            name: 'image_to_image',
            taskReferenceName: 'image_to_image_fn5q5x94',
            type: 'SIMPLE',
            inputParameters: {
              modelId: '2284647e3596e78512606d22e2728cd2',
              prompt: 'perfume, yellow flower:1.3,  simple background <lora:81ea76b9aaa49b75ce4321e8a5f20ffc:0.7>',
              negativePrompt: 'EasyNegative',
              initImages: '${workflow.input.qp9ho86z}',
              batchCount: 3,
              width: 768,
              height: 1152,
              samplingStep: 20,
              cfgScale: 7,
              imageCfgScale: 0.7,
              mask: '${rembg_gy19jwbe.output.imageUrl}',
              inpaintingMaskInvert: true,
              maskBlur: 4,
              inpaintingFill: 1,
              inpaintFullRes: true,
              inpaintFullResPadding: 32,
              seed: -1,
              samplerName: 'DPM++ 2M SDE Karras',
              restoreFaces: false,
              controlNetEnabled: true,
              controlNetModule: 'lineart',
              controlNetModel: 'control_v11p_sd15_lineart [43d4be0d]',
              controlNetWeight: 1,
              controlNetGuidanceStrength: 1,
              controlNetInputImage: '${workflow.input.qp9ho86z}',
              controlNetNoDetectmap: true,
            },
          },
          {
            name: 'code',
            taskReferenceName: 'code_jdgsyawb',
            type: 'SIMPLE',
            inputParameters: {
              parameters: {
                arr: '${image_to_image_fn5q5x94.output.result}',
              },
              sourceCode: 'return $.arr[0];',
            },
            __alias: {
              title: '列表转字符串',
            },
          },
          {
            name: 'upscale',
            taskReferenceName: 'upscale_ap3nw8v6',
            type: 'SIMPLE',
            inputParameters: {
              model: 'ESRGAN_4x',
              image: '${code_jdgsyawb.output.data}',
              scale: 2,
            },
          },
          {
            name: 'code',
            taskReferenceName: 'code_ascc1g0v',
            type: 'SIMPLE',
            inputParameters: {
              parameters: {
                overlayImg: '${upscale_ap3nw8v6.output.result}',
              },
              sourceCode: 'return [$.overlayImg];',
            },
            __alias: {
              title: '字符串转数组',
            },
          },
          {
            name: 'save_image',
            taskReferenceName: 'save_image_k5k2ni5l',
            type: 'SIMPLE',
            inputParameters: {
              urls: '${code_ascc1g0v.output.data}',
              name: '.png',
              option: 'random',
              start: 1,
              end: 10,
            },
          },
        ],
        schemaVersion: null,
      },
      workflowId: '656dd42e36c95999b726c7df',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '6566ffb39f17bc4d70144f26',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1701248947384,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:👍:#fef8a3',
      isDeleted: false,
      masterWorkflowId: null,
      name: '示例应用',
      output: [],
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1706441775958,
      validated: true,
      validationIssues: [],
      variables: [
        {
          displayName: '测试',
          type: 'string',
          default: '你好，请写一行算式',
          name: '18lkuxwc',
        },
      ],
      version: 1,
      workflowDef: {
        name: '6566ffb39f17bc4d70144f26',
        tasks: [
          {
            name: 'chatgpt_with_prompt',
            type: 'SIMPLE',
            taskReferenceName: 'chatgpt_with_prompt_6v6s2b1j',
            inputParameters: {
              systemMessage: '你是一名智能助理',
              humanMessage: '${workflow.input.18lkuxwc}',
              modelType: 'gpt3',
              __commonConfig: {
                timeoutSeconds: 3575,
              },
            },
            __alias: {
              title: 'GPT',
              icon: 'emoji:💬:#434343',
            },
          },
        ],
      },
      workflowId: '6566ffb39f17bc4d70144f26',
      md5: 'fda22af3b60afc0f50d6ec2946949665',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '655f2597f8e7d71b08ace1c1',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1700734359478,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🍀:#ceefc5',
      isDeleted: false,
      masterWorkflowId: null,
      name: 'Socket 测试',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1700734389888,
      validated: true,
      validationIssues: [],
      variables: [],
      version: 1,
      workflowDef: {
        name: '655f2597f8e7d71b08ace1c1',
        tasks: [
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_j9lgjoum',
            inputParameters: {
              parameters: {},
              sourceCode: "console.log('测试111');\n\nreturn '测试';",
            },
          },
        ],
      },
      workflowId: '655f2597f8e7d71b08ace1c1',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '655966dda4d01a1cb926320b',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1700357853061,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '使用GPT对待测评文本模型进行单个领域维度的单项指标测评，产生测评分数',
      forkFromId: '6539cd2ea8cb4dd366c0fa07',
      hidden: false,
      iconUrl: 'emoji:🦉:#d9caf8',
      isDeleted: false,
      masterWorkflowId: null,
      name: '文本模型测评-单领域单指标_clone',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1700357853061,
      variables: [
        {
          type: 'string',
          displayName: 'eval_url',
          default: 'https://static.infmonkeys.com/frame/files/upload/1697792211925_workflow.json',
          name: '0uje4iax',
        },
      ],
      version: 1,
      workflowDef: {
        tasks: [
          {
            name: 'send_request',
            taskReferenceName: 'send_request_o9q3n7m7',
            type: 'SIMPLE',
            inputParameters: {
              url: '${workflow.input.0uje4iax}',
              method: 'GET',
              content_type: 'application/json',
              data: null,
              response_type: 'application/json',
            },
          },
          {
            name: 'code',
            taskReferenceName: 'code_u0cwg7j8',
            type: 'SIMPLE',
            inputParameters: {
              parameters: {
                question: '${send_request_o9q3n7m7.output.data}',
              },
              sourceCode: 'const responses = $.question.map(item => item.instruction);\nreturn responses',
            },
            __alias: {
              title: '抽取instruction',
            },
          },
          {
            name: 'code',
            type: 'SIMPLE',
            taskReferenceName: 'code_jvg94ksi',
            inputParameters: {
              parameters: {
                question: '${send_request_o9q3n7m7.output.data}',
              },
              sourceCode: 'const responses = $.question.map(item => item.output);\nreturn responses\n',
            },
            __alias: {
              title: '抽取output',
              icon: 'emoji:🖥️:#434343',
            },
          },
          {
            name: 'do_while',
            taskReferenceName: 'do_while_sw8we7wj',
            type: 'DO_WHILE',
            loopCondition: "if ($.do_while_sw8we7wj['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'code',
                type: 'SIMPLE',
                taskReferenceName: 'code_eyrnvzjf',
                inputParameters: {
                  parameters: {
                    arrnow: '${code_jvg94ksi.output.data}',
                    loopIndex: '${do_while_sw8we7wj.output.iteration}',
                  },
                  sourceCode: 'return $.arrnow[$.loopIndex - 1];',
                },
              },
              {
                name: 'chat_with_baichuan2',
                taskReferenceName: 'chat_with_baichuan2_g1xg5qks',
                type: 'SIMPLE',
                inputParameters: {
                  text: '${do_while_sw8we7wj_loopItemRef.output.result}',
                },
              },
              {
                name: 'chatgpt_with_prompt',
                taskReferenceName: 'chatgpt_with_prompt_bqdgm9ri',
                type: 'SIMPLE',
                inputParameters: {
                  systemMessage:
                    '你现在要扮演一个评测专家为一个答案进行评价,你要评价的指标是问题答案的正确性,评分标准如下:10分:答案完全正确,和标准答案一致。8分:答案基本正确,只有非关键细节上与标准答案有略微出入。6分:答案含有一定错误,但主要点表达正确。4分:答案与标准答案存在较大出入,部分关键信息错误。2分:答案与标准答案相关性不强,大部分关键信息都有错误。0分:答案与标准答案毫无关联,完全错误。当前的问题是“{question}”,标准答案是“{answer}”,当前的答案是“{response}”。\\n 必须注意：请你给出0-10分的评价分数，仅仅包含数字，不允许包含任何其他信息。',
                  humanMessage:
                    '当前的问题是“{question}”：${do_while_sw8we7wj_loopItemRef.output.result} 这是这是当前的答案“{response}”：${chat_with_baichuan2_g1xg5qks.output.response} \n标准答案是“{answer}”:${code_eyrnvzjf.output.data}',
                  modelType: 'gpt3',
                },
                __alias: {
                  title: '正确性评分',
                  icon: 'emoji:💬:#fef8a3',
                },
              },
            ],
            inputParameters: {
              mode: 'list',
              listToLoopOver: '${code_u0cwg7j8.output.data}',
              parameters: {},
            },
            __alias: {
              title: '问题循环',
            },
          },
          {
            name: 'collect_dowhile_output',
            taskReferenceName: 'collect_dowhile_output_he7n0pas',
            type: 'SIMPLE',
            inputParameters: {
              doWhileTaskReferenceName: 'do_while_sw8we7wj',
            },
          },
          {
            name: 'code',
            taskReferenceName: 'code_rntiwohr',
            type: 'SIMPLE',
            inputParameters: {
              parameters: {
                response: '${collect_dowhile_output_he7n0pas.output.data}',
              },
              sourceCode:
                'const responses = $.response.chatgpt_with_prompt_bqdgm9ri.map(item => item.response);\nconst regexp = /\\d+/;\nreturn responses.map(r => {\n    try {\n        const res = Number(r.match(regexp)[0]);\n        if (res >= 0 && res <= 10) {\n            return res;\n        }\n        throw new Error();\n    } catch {\n        return 5;\n    }\n});',
            },
            __alias: {
              title: '抽取response',
            },
          },
        ],
        schemaVersion: null,
      },
      workflowId: '655966dda4d01a1cb926320b',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '653b9fe8a06d2676d5c5ec94',
      activated: true,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1698406376622,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🥵:#f2c1be',
      isDeleted: false,
      masterWorkflowId: null,
      name: '变态渲染',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1704699752390,
      validated: true,
      validationIssues: [],
      variables: [],
      version: 1,
      workflowDef: {
        name: '653b9fe8a06d2676d5c5ec94',
        tasks: [
          {
            name: 'human',
            type: 'HUMAN',
            taskReferenceName: 'human_8jhhmoqc',
            inputParameters: {
              diplayContent: [],
              outputType: 'array',
              arrayJoinSeparator: null,
            },
          },
          {
            name: 'do_while',
            type: 'DO_WHILE',
            taskReferenceName: 'do_while_y3nlclli',
            inputParameters: {
              mode: 'expression',
              listToLoopOver: null,
            },
            loopCondition: "if ($.do_while_y3nlclli['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'sub_workflow',
                taskReferenceName: 'sub_workflow_nested_rq9jvvmd',
                type: 'SUB_WORKFLOW',
                inputParameters: {
                  name: '654666ef38713208570d94da',
                  version: 1,
                },
              },
            ],
          },
        ],
      },
      workflowId: '653b9fe8a06d2676d5c5ec94',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '64f5a18854279dbd3057cc85',
      active: false,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1693819272098,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:🔄:#434343',
      isDeleted: false,
      masterWorkflowId: null,
      name: '循环嵌套测试',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1706458602244,
      validated: true,
      validationIssues: [],
      variables: [
        {
          type: 'collection',
          displayName: 'Prompt',
          default: ['test', 'demo'],
          name: '5xuzk2yk',
        },
        {
          type: 'collection',
          displayName: 'Prompt2',
          default: ['a', 'b'],
          name: 'thtzvqsg',
        },
      ],
      version: 1,
      workflowDef: {
        name: '64f5a18854279dbd3057cc85',
        tasks: [
          {
            name: 'do_while',
            type: 'DO_WHILE',
            taskReferenceName: 'do_while_9hrxymp9',
            inputParameters: {
              mode: 'expression',
              listToLoopOver: '',
              loopCondition: "if ($._TaskRefName_['iteration'] < 1) { false; } else { true; }",
            },
            loopCondition: "if ($.do_while_9hrxymp9['iteration'] < 1) { false; } else { true; }",
            loopOver: [
              {
                name: 'sub_workflow',
                type: 'SUB_WORKFLOW',
                taskReferenceName: 'sub_workflow_nested_64f9e8c071f2c40fffcf8551',
                inputParameters: {
                  name: '64f9e8c071f2c40fffcf8551',
                  version: 1,
                },
              },
            ],
          },
        ],
      },
      workflowId: '64f5a18854279dbd3057cc85',
      md5: '3c2da1c4f7de308eaf08ef8600e3453d',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
    {
      _id: '64f1819954279dbd3057cc56',
      active: false,
      assetTags: [],
      assetType: 'workflow',
      createdTimestamp: 1693548953945,
      creatorUserId: '6433d199eb120f3c33f0c28f',
      description: '',
      hidden: false,
      iconUrl: 'emoji:😐:#434343',
      isDeleted: false,
      masterWorkflowId: null,
      name: '子流程嵌套测试',
      teamId: '6433d19aeb120fec53f0c290',
      updatedTimestamp: 1693548992469,
      variables: [],
      version: 1,
      workflowDef: {
        tasks: [
          {
            name: 'human',
            taskReferenceName: 'human_sah4nhmc',
            type: 'HUMAN',
            inputParameters: {
              diplayContent: ['测试'],
            },
          },
        ],
      },
      workflowId: '64f1819954279dbd3057cc56',
      user: {
        _id: '6433d199eb120f3c33f0c28f',
        photo: 'https://static.infmonkeys.com/avatars/1701172582037.png',
        name: '打工伏',
        phone: '171****1023',
      },
      team: {
        _id: '6433d19aeb120fec53f0c290',
        name: 'ALL IN BOOM',
        logoUrl: 'https://static.infmonkeys.com/frame/files/upload/1697544816876_team_logo/1697544790569.png',
      },
    },
  ],
  total: 17,
  page: 1,
  limit: 24,
};
