/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as LoginImport } from './pages/login'
import { Route as IndexImport } from './pages/index'
import { Route as ComponentsTagImport } from './pages/components/tag'
import { Route as ComponentsButtonImport } from './pages/components/button'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsTagRoute = ComponentsTagImport.update({
  path: '/components/tag',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsButtonRoute = ComponentsButtonImport.update({
  path: '/components/button',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/components/button': {
      preLoaderRoute: typeof ComponentsButtonImport
      parentRoute: typeof rootRoute
    }
    '/components/tag': {
      preLoaderRoute: typeof ComponentsTagImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  ComponentsButtonRoute,
  ComponentsTagRoute,
])

/* prettier-ignore-end */
