name: Publish Server Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish Docker image to Docker Hub and Harbor
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}
      build_time: ${{ steps.calc_time.outputs.duration }}
    steps:
      - name: Start timer
        id: start_time
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract tag name as RELEASE_TAG
        id: extract_tag
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: infmonkeys/monkeys

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/server/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save Docker image to a tar file
        run: |
          docker save infmonkeys/monkeys:${RELEASE_TAG} -o monkeys-${RELEASE_TAG}.tar.gz

      - name: Install ossutil And Upload to Aliyun OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.5/ossutil64 && chmod 755 ossutil64
          ./ossutil64 config --endpoint "$OSS_ENDPOINT" --access-key-id "$OSS_ACCESS_KEY_ID" --access-key-secret "$OSS_ACCESS_KEY_SECRET"
          ./ossutil64 cp monkeys-${RELEASE_TAG}.tar.gz oss://$OSS_BUCKET/docker/monkeys/monkeys/monkeys-${RELEASE_TAG}.tar.gz

      - name: Calculate build duration
        id: calc_time
        if: always()
        run: |
          end_time=$(date +%s)
          start_time=${{ steps.start_time.outputs.start_time }}
          duration=$((end_time - start_time))
          echo "duration=$duration" >> $GITHUB_OUTPUT

  notify:
    needs: push_to_registry
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: colour93/ci-notify-feishu@main
        with:
          feishu_template_id: ${{ vars.FEISHU_NOTIFY_TEMPLATE_ID }}
          feishu_template_version_name: ${{ vars.FEISHU_NOTIFY_TEMPLATE_VERSION }}
          feishu_webhook_url: ${{ secrets.FEISHU_NOTIFY_WEBHOOK_URL }}
          build_result: ${{ needs.push_to_registry.result }}
          ci_target: Server
          ci_target_image: infmonkeys/monkeys
          ci_target_tag: ${GITHUB_REF#refs/tags/}
          build_time: ${{ needs.push_to_registry.outputs.build_time }} 