name: Publish Server(Multi Tenancy) Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish Docker image to Docker Hub and Harbor
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Harbor
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: ${{ secrets.HARBOR_REGISTRY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: infmonkeys/monkeys-multi-tenancy

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/server/Dockerfile-multi-tenancy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image to Harbor
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/server/Dockerfile-multi-tenancy
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/infmonkeys/monkeys-multi-tenancy:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save Docker image to a tar file
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          docker save infmonkeys/monkeys-multi-tenancy:$RELEASE_TAG -o monkeys-multi-tenancy-$RELEASE_TAG.tar.gz

      - name: Install ossutil And Upload to Aliyun OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          wget https://gosspublic.alicdn.com/ossutil/1.7.5/ossutil64 && chmod 755 ossutil64
          ./ossutil64 config --endpoint "$OSS_ENDPOINT" --access-key-id "$OSS_ACCESS_KEY_ID" --access-key-secret "$OSS_ACCESS_KEY_SECRET"
          ./ossutil64 cp monkeys-multi-tenancy-$RELEASE_TAG.tar.gz oss://$OSS_BUCKET/docker/monkeys/monkeys/monkeys-multi-tenancy-$RELEASE_TAG.tar.gz
